"""
ElevenLabs Only Test - Test just ElevenLabs TTS functionality
Focused test for voice synthesis without other dependencies
"""  # [NRS-810]

import os  # [NRS-810]
import asyncio  # [NRS-810]

async def test_elevenlabs_only():  # [NRS-810]
    """Test only ElevenLabs functionality"""  # [NRS-810]
    print("🎯 ElevenLabs TTS Test")  # [NRS-810]
    print("=" * 25)  # [NRS-810]
    
    # Step 1: Check if we can import elevenlabs  # [NRS-810]
    print("📦 Testing ElevenLabs import...")  # [NRS-810]
    try:  # [NRS-810]
        import elevenlabs  # [NRS-810]
        print("✅ ElevenLabs library: Available")  # [NRS-810]
    except ImportError as e:  # [NRS-810]
        print(f"❌ ElevenLabs library: {e}")  # [NRS-810]
        return False  # [NRS-810]
    
    # Step 2: Check API key  # [NRS-810]
    print("🔑 Checking API key...")  # [NRS-810]
    api_key = os.getenv('ELEVENLABS_API_KEY')  # [NRS-810]
    if api_key:  # [NRS-810]
        print(f"✅ API Key: Set ({api_key[:8]}...)")  # [NRS-810]
    else:  # [NRS-810]
        print("⚠️  API Key: Not set")  # [NRS-810]
        print("   To set: $env:ELEVENLABS_API_KEY='your_key_here'")  # [NRS-810]
        # Let's continue with a test key for structure testing  # [NRS-810]
        api_key = "test_key_for_structure_test"  # [NRS-810]
    
    # Step 3: Test basic ElevenLabs client creation  # [NRS-810]
    print("🔧 Testing ElevenLabs client creation...")  # [NRS-810]
    try:  # [NRS-810]
        from elevenlabs.client import ElevenLabs  # [NRS-810]
        client = ElevenLabs(api_key=api_key)  # [NRS-810]
        print("✅ ElevenLabs client: Created")  # [NRS-810]
    except Exception as e:  # [NRS-810]
        print(f"❌ ElevenLabs client: {e}")  # [NRS-810]
        return False  # [NRS-810]
    
    # Step 4: Test our TTS configuration  # [NRS-810]
    print("⚙️  Testing TTS configuration...")  # [NRS-810]
    try:  # [NRS-810]
        from jarvis.tts_engine import TTSConfig  # [NRS-810]
        config = TTSConfig(  # [NRS-810]
            provider='elevenlabs',  # [NRS-810]
            api_key=api_key,  # [NRS-810]
            voice_id='jarvis',  # [NRS-810]
            model='eleven_multilingual_v2'  # [NRS-810]
        )  # [NRS-810]
        print("✅ TTS Config: Created")  # [NRS-810]
    except Exception as e:  # [NRS-810]
        print(f"❌ TTS Config: {e}")  # [NRS-810]
        return False  # [NRS-810]
    
    # Step 5: Test TTS engine creation (but don't call API)  # [NRS-810]
    print("🚀 Testing TTS engine creation...")  # [NRS-810]
    try:  # [NRS-810]
        from jarvis.tts_engine import TTSEngine  # [NRS-810]
        tts = TTSEngine(config)  # [NRS-810]
        print("✅ TTS Engine: Created")  # [NRS-810]
    except Exception as e:  # [NRS-810]
        print(f"❌ TTS Engine: {e}")  # [NRS-810]
        return False  # [NRS-810]
    
    # Step 6: If real API key, test actual synthesis  # [NRS-810]
    real_api_key = os.getenv('ELEVENLABS_API_KEY')  # [NRS-810]
    if real_api_key and real_api_key != "test_key_for_structure_test":  # [NRS-810]
        print("🎵 Testing real voice synthesis...")  # [NRS-810]
        try:  # [NRS-810]
            # Create new engine with real API key  # [NRS-810]
            real_config = TTSConfig(  # [NRS-810]
                provider='elevenlabs',  # [NRS-810]
                api_key=real_api_key,  # [NRS-810]
                voice_id='jarvis',  # [NRS-810]
                model='eleven_multilingual_v2'  # [NRS-810]
            )  # [NRS-810]
            real_tts = TTSEngine(real_config)  # [NRS-810]
            
            # Try to synthesize short text  # [NRS-810]
            test_text = "Hello, this is Jarvis testing."  # [NRS-810]
            audio = await real_tts.text_to_speech(test_text)  # [NRS-810]
            
            if audio is not None and len(audio) > 0:  # [NRS-810]
                print(f"✅ Voice synthesis: Success ({len(audio)} samples)")  # [NRS-810]
                
                # Try to save audio file  # [NRS-810]
                try:  # [NRS-810]
                    import soundfile as sf  # [NRS-810]
                    sf.write("test_voice.wav", audio, 16000)  # [NRS-810]
                    print("💾 Audio saved to: test_voice.wav")  # [NRS-810]
                except:  # [NRS-810]
                    print("💾 Audio generated but not saved (soundfile issue)")  # [NRS-810]
                    
                return True  # [NRS-810]
            else:  # [NRS-810]
                print("❌ Voice synthesis: No audio generated")  # [NRS-810]
                return False  # [NRS-810]
                
        except Exception as e:  # [NRS-810]
            print(f"❌ Voice synthesis: {e}")  # [NRS-810]
            return False  # [NRS-810]
    else:  # [NRS-810]
        print("ℹ️  Skipping voice synthesis (no real API key)")  # [NRS-810]
        print("✅ Structure test: All components ready")  # [NRS-810]
        return True  # [NRS-810]

if __name__ == "__main__":  # [NRS-810]
    result = asyncio.run(test_elevenlabs_only())  # [NRS-810]
    
    print("\n" + "=" * 25)  # [NRS-810]
    if result:  # [NRS-810]
        print("🎉 ElevenLabs TTS: Ready!")  # [NRS-810]
        print("📝 Set ELEVENLABS_API_KEY for voice synthesis")  # [NRS-810]
    else:  # [NRS-810]
        print("🔧 ElevenLabs TTS: Needs fixing")  # [NRS-810]